---
# Install packages
general_apts:
  - name: git
  - name: tmux
  - name: binutils
  - name: htop
  - name: curl

# Install pentesting packages
pentest_apts:
  - name: socat
  - name: chromium-browser
  - name: httpie
  - name: jq
  - name: nmap
  - name: exiftool
  - name: ffuf
  - name: gobuster
  - name: proxychains
  - name: whatweb
  - name: nikto
  - name: sqlmap
  - name: pipx
  - name: wireshark
  - name: tshark
  - name: sslscan

# General snaps
general_snaps:
  - name: obsidian
    classic: true

# Social snaps
social_snaps:
  - name: slack
  - name: discord
  - name: signal-desktop

# Install pentesting snaps
pentest_snaps:
  - name: metasploit-framework

# Install pipx tools
pentest_pipx:
  - name: impacket
    url: 'git+https://github.com/fortra/impacket.git'
  - name: autorecon
    url: 'git+https://github.com/Tib3rius/AutoRecon.git'
  - name: crackmapexec
    url: 'git+https://github.com/mpgn/CrackMapExec.git'

# Copy dot files
dotfiles:
  - tmux.conf

# Clone github repositories to user directory
git_repos:
  - name: 'SecLists'
    repo: 'https://github.com/danielmiessler/SecLists.git'
  - name: 'PayloadsAllTheThings'
    repo: 'https://github.com/swisskyrepo/PayloadsAllTheThings.git'
  - name: 'GTFOBins'
    repo: 'https://github.com/GTFOBins/GTFOBins.github.io.git'
  - name: 'LOLBAS'
    repo: 'https://github.com/LOLBAS-Project/LOLBAS.git'
  - name: 'PEASS-ng'
    repo: 'https://github.com/carlospolop/PEASS-ng.git'

# Configuration for Burpsuite
# burpsuite_edition: 'pro'                      # uncomment for pro
# burpsuite_pro_license_key: 'xxx'              # enter license key for pro
burpsuite_user: '{{ ansible_user_id }}'         # required for pro and community

# Configuration for Visual Studio Code
users:
  - username: '{{ ansible_user_id }}'
    visual_studio_code_settings_overwrite: 'true'
    visual_studio_code_settings: {
      "editor.rulers": [80, 100, 120],
      "editor.renderWhitespace": true
    }
    visual_studio_code_extensions:
      - 'streetsidesoftware.code-spell-checker'
      - 'GitHub.copilot'
      - 'GitHub.codespaces'
      - 'GitHub.vscode-github-actions'