---
- name: "Pentester Workstation Playbook (PWP)"
  hosts: all
  ignore_errors: true
  
  vars_files:
  - config.yml

  pre_tasks:
  # Update and upgrade system with full-upgrade
  - name: pre-run | update apt cache
    ansible.builtin.apt:
      cache_valid_time: 86400
    become: true
    become_method: sudo
    when: ansible_distribution in ["Ubuntu"]

  # Run external ansible galaxy roles
  roles:
    - role: iesplin.burp_suite
      tags: ['burpsuite']
    - role: gantsign.visual-studio-code
      tags: ['vscode']
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']

  # Run tasks from tasks directory
  tasks:
  - import_tasks: tasks/disable-services.yml
  - import_tasks: tasks/apts.yml
  - import_tasks: tasks/snaps.yml
  - import_tasks: tasks/pipx.yml
  - import_tasks: tasks/git-repos.yml
  - import_tasks: tasks/appearance.yml
    tags: ['appearance']
  - import_tasks: tasks/ufw.yml
    tags: ['firewall']
