---
# Install packages specified in config.yml
- name: tasks | apt.yml | install general packages
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  become: true
  become_method: sudo
  with_items: "{{ general_apts }}"

  # Install pentesting packages specified in config.yml
- name: tasks | apt.yml | install pentesting packages
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  become: true
  become_method: sudo
  with_items: "{{ pentest_apts }}"
  tags: ['pentest']