---
# Copy dotfiles from files
# Find a way to manage this from git repo
- name: tasks | dotfiles.yml | copy dotfiles from files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.{{ item }}"
    # owner: "{{ ansible_user_id }}"
    # group: "{{ ansible_user_id }}"
    # mode: 0664
  with_items: "{{ dotfiles }}"