---
# Install general snaps from config.yml
- name : tasks | snaps.yml | install general snaps
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    classic: "{{ item.classic | default('false') }}"
  become: true
  become_method: sudo
  with_items: "{{ general_snaps }}"
  tags: ['always']

# Install pentesting packages specified in config.yml
- name : tasks | snaps.yml | install pentesting packages from snap
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    classic: "{{ item.classic | default('false') }}"
  become: true
  become_method: sudo
  with_items: "{{ pentest_snaps }}"
  tags: ['pentest']

# Install social snaps from config.yml
- name : tasks | snaps.yml | install social snaps
  community.general.snap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    classic: "{{ item.classic | default('false') }}"
  become: true
  become_method: sudo
  with_items: "{{ social_snaps }}"
  tags: ['social']