---
# install ufw with apt
- name: tasks | ufw.yml | install ufw with apt
  ansible.builtin.apt:
    name: 'ufw'
    state: 'present'
  become: true
  become_method: 'sudo'

# enable ufw
- name: tasks | ufw.yml | enable ufw
  community.general.ufw:
    state: enabled
    policy: deny
  become: true
  become_method: sudo

# enable rsyslog
- name: tasks | ufw.yml | enable rsyslog service
  ansible.builtin.service:
    name: rsyslog
    enabled: yes
    state: started
  become: true
  become_method: sudo

# log syn packets
- name: tasks | ufw.yml | log syn packets on after.rules
  ansible.builtin.lineinfile:
    path: '/etc/ufw/after.rules'
    line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
    insertbefore: '^COMMIT'
  become: true
  become_method: 'sudo'

  # allow ssh connections
- name: tasks | ufw.yml | allow ssh connections
  community.general.ufw:
    rule: allow
    port: '22'
    proto: 'tcp'
  become: true
  become_method: sudo