---
name: Continuous Integration (CI)
'on':
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        molecule_distro: ['ubuntu1804', 'ubuntu2004', 'ubuntu2204']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule yamllint ansible-lint jmespath pexpect defusedxml
          ansible-galaxy install -r requirements.yml
      
      - name: Test playbook syntax
        run: ansible-playbook main.yml --syntax-check

      - name: Test playbook defaults
        run: ansible-playbook main.yml --skip-tags=appearance
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
